#! /bin/bash

with=${1-with}
shift

autoreconf

cflags=''
config_args=($with-chez-scheme --without-jpeg --without-makeinfo AM_DEFAULT_VERBOSITY=0)

if [[ $with == --with ]]; then
  cflags+='-Werror=implicit-function-declaration -Werror=nested-externs -fno-builtin'
  cflags+=' -O0 -finline-functions -gdwarf-2 -g3'
  #cflags+=' -O1 -gdwarf-2 -g2 -fsanitize=address -fno-omit-frame-pointer'
  config_args+=(--enable-checking=yes CANNOT_DUMP=yes --without-threads CFLAGS="$cflags")
fi

./configure "${config_args[@]}"
