#! /bin/bash

with=${1-with}
shift

CFLAGS='-O1 -g -Werror=implicit-function-declaration -Werror=nested-externs'

autoreconf
./configure --enable-checking=yes --$with-chez-scheme CANNOT_DUMP=yes CFLAGS="$CFLAGS" "$@"
