#! /bin/bash

with=${1-with}
shift

CFLAGS='-O0 -g -Werror=implicit-function-declaration -Werror=nested-externs'

autoreconf
./configure --enable-checking=yes --$with-chez-scheme CFLAGS="$CFLAGS" "$@"
