#! /bin/bash

#if make -C src -j temacs 2>/dev/null || make -C src -k temacs; then
if make -C src -j temacs; then
  true
#   EMACS_CMD="src/emacs --batch"
  EMACS_CMD="src/temacs --batch --load loadup"
  GDB=
  if [[ $TERM != dumb ]]; then
    GDB="gdb -ex r --args"
  fi
  $GDB $EMACS_CMD
  
#   $GDB $EMACS_CMD --eval \
#     "
# (progn
#  (setq garbage-collection-messages t)
#  (message \"after-idle: %S\"
#    (prog1 (scheme-funcall 'after-idle (cons nil nil))
#    (garbage-collect))))"
  #src/emacs -Q --batch --eval "(message \"after-idle: %S\" (scheme-funcall 'after-idle))"
fi
