SCHEME_FPTR_DEF("hashtable?", hashtablep);
SCHEME_FPTR_DEF("hashtable-ref", hashtable_ref);
SCHEME_FPTR_DEF("eq-hash", eq_hash);
SCHEME_FPTR_DEF("hashtable-values", hashtable_values);
SCHEME_FPTR_DEF("print-to-bytevector", print_to_bytevector);
SCHEME_FPTR_DEF("object-is-str?", object_is_str);
SCHEME_FPTR_DEF("getprop", getprop);
SCHEME_FPTR_DEF("putprop", putprop);
#undef SCHEME_FPTR_DEF
