SCHEME_FPTR_DEF("hashtable?", hashtablep);
SCHEME_FPTR_DEF("hashtable-ref", hashtable_ref);
SCHEME_FPTR_DEF("eq-hash", eq_hash);
SCHEME_FPTR_DEF("hashtable-values", hashtable_values);
SCHEME_FPTR_DEF("print-to-bytevector", print_to_bytevector);
SCHEME_FPTR_DEF("object-is-str?", object_is_str);
SCHEME_FPTR_DEF("getprop", getprop);
SCHEME_FPTR_DEF("putprop", putprop);
SCHEME_FPTR_DEF("generic-get", generic_get);
SCHEME_FPTR_DEF("generic-put!", generic_put);
SCHEME_FPTR_DEF("utf8->string", utf8_to_string);
SCHEME_FPTR_DEF("string->utf8", string_to_utf8);
#undef SCHEME_FPTR_DEF
